In [1]:
import numpy as np

In [11]:
arr = np.array([1,2,3])

In [12]:
# dimension and shape of an array

arr.ndim

1

In [13]:
a = np.array(420)
a.ndim


0

In [16]:
d = np.array([[]])
d.ndim
d.shape


(1, 0)

In [19]:
l = []

for i in range(10):
    l.append(i)

print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [22]:
range = np.arange(1,10,2)
range

array([1, 3, 5, 7, 9])

In [23]:
# np.linspace(start, stop, no of values b/w them)

arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
# logarithmic scale array
# np.logspace(starting power, ending power, no of values b/w them)

arr = np.logspace(1, 3, 3)
arr

array([  10.,  100., 1000.])

In [25]:
# np.zeros => array full of zeros

arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.zeros([2,3])       # 2 rows, 3 columns
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
arr = np.ones(10)
arr


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr = np.ones([2,3], int)       # we can also pass data type
arr


array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
# create an array full of any value
arr = np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr = np.full([2,4], 4.2)       # [row, column, default value]
arr


array([[4.2, 4.2, 4.2, 4.2],
       [4.2, 4.2, 4.2, 4.2]])

In [37]:
# uninitialized array
arr = np.empty([2,3])
arr

array([[3.47739835e-081, 8.08291397e-321, 0.00000000e+000],
       [1.12317469e-311, 0.00000000e+000, 7.56571287e-307]])

In [40]:
# generate random floats

arr = np.random.rand(2)
arr

array([0.31651619, 0.74928327])

In [41]:
arr = np.random.randn(2,3)        # random floats from standard normal distribution
arr


array([[ 1.3051873 , -0.91921472, -0.0065601 ],
       [-1.23878414, -0.16913895, -1.31999918]])

In [43]:
arr = np.random.randint(10, 100)        # random int
arr

18

In [44]:
arr = np.random.randint(10, 100, size=[2,3])        # random int
arr


array([[76, 30, 96],
       [36, 88, 95]], dtype=int32)

In [ ]:
arr = np.arange(10)
arr